Intermediate commit:
fixed (probably) a compilation bug with intel compiler ifort/ifx > 2019
(tested on 2021). For some reason, if variables are bound to c via
iso_c_binding, the intel compiler creates duplicate symbols.
E.g. Nspin, Norb in ED_INPUT_VARS.
If another module imports ED_INPUT_VARS and a function there
defined tries to use input parameters with defined shapes containing
Nspin or Norb, the function is compiled, but any call to it results in a
compilation error:

`error #7556: The external name for this symbol conflicts
with a previously declared external name.   [ED_INPUT_VARS^NORB]`

The fix provided here uses a "use ED_INPUT_VARS, only: Nspin,Norb"
inside the offending functions. This seems to remove the issue. To avoid
errors in unaffected compilation environments, the statement is embedded
in a precompiler flag for the intel compilers.